export const COLORS = ["red", "blue", "yellow", "green", "black"];
export const WIN_SCORE = 18;
export const EVOLUTION_DISCOUNT = 1;

export const TRAINERS = [
  { id: "ash", name: "지우", title: "무작정 도전", avatar: "🧢", bonus: "yellow", perk: { reserveWild: 2 }, desc: "포켓몬을 손에 보관할 때 마스터볼을 2개 받습니다." },
  { id: "misty", name: "이슬이", title: "물의 명수", avatar: "💧", bonus: "blue", perk: { sameColorThreshold: 3 }, desc: "같은 색 볼 2개를 공급처에 3개만 남아도 가져올 수 있습니다." },
  { id: "brock", name: "웅이", title: "바위의 수호자", avatar: "🪨", bonus: "black", perk: { tokenLimit: 12 }, desc: "차례 종료 시 포켓볼을 12개까지 보유할 수 있습니다." },
  { id: "erika", name: "민화", title: "풀꽃의 인도자", avatar: "🌿", bonus: "green", perk: { evolutionDiscount: 2 }, desc: "진화 비용이 모든 색 2개씩 할인됩니다." },
  { id: "blaine", name: "강연", title: "불꽃의 퀴즈왕", avatar: "🔥", bonus: "red", perk: { specialDiscount: 1 }, desc: "희귀·전설 포켓몬의 색 비용이 모든 색 1개씩 줄어듭니다." },
  { id: "sabrina", name: "나츠메", title: "예지의 초능력자", avatar: "🔮", bonus: "blue", perk: { reserveLimit: 4 }, desc: "포켓몬을 손에 4장까지 보관할 수 있습니다." },
  { id: "blue", name: "그린", title: "최강의 라이벌", avatar: "😎", bonus: "red", perk: { tierThreeBonus: 1 }, desc: "3단계 포켓몬을 포획할 때마다 명성 1점을 더 받습니다." },
  { id: "surge", name: "마티스", title: "전격 중위", avatar: "⚡", bonus: "yellow", perk: { badgeRelief: 1 }, desc: "체육관 배지 획득 조건이 모든 색 1개씩 낮아집니다." },
];

export const BADGES = [
  { id: "boulder", name: "그레이배지", leader: "비주기 체육관", icon: "🪨", points: 3, need: { black: 4, red: 3 } },
  { id: "cascade", name: "블루배지", leader: "회색 체육관", icon: "💧", points: 3, need: { blue: 4, green: 3 } },
  { id: "thunder", name: "오렌지배지", leader: "갈색 체육관", icon: "⚡", points: 3, need: { yellow: 4, red: 3 } },
  { id: "rainbow", name: "레인보우배지", leader: "무지개 체육관", icon: "🌈", points: 3, need: { green: 4, blue: 3 } },
  { id: "soul", name: "핑크배지", leader: "연분홍 체육관", icon: "💗", points: 3, need: { green: 3, black: 2, blue: 2 } },
  { id: "marsh", name: "골드배지", leader: "노랑 체육관", icon: "🔮", points: 3, need: { blue: 3, yellow: 2, red: 2 } },
  { id: "volcano", name: "마블배지", leader: "홍련 체육관", icon: "🔥", points: 3, need: { red: 3, yellow: 2, black: 2 } },
  { id: "earth", name: "그린배지", leader: "상록 체육관", icon: "🌿", points: 3, need: { black: 3, green: 2, yellow: 2 } },
];

const families = [
  [["피츄", 172], ["피카츄", 25], ["라이츄", 26]], [["파이리", 4], ["리자드", 5], ["리자몽", 6]], [["꼬부기", 7], ["어니부기", 8], ["거북왕", 9]], [["이상해씨", 1], ["이상해풀", 2], ["이상해꽃", 3]], [["애버라스", 246], ["데기라스", 247], ["마기라스", 248]], [["고오스", 92], ["고우스트", 93], ["팬텀", 94]], [["미뇽", 147], ["신뇽", 148], ["망나뇽", 149]], [["잉어킹", 129], ["갸라도스", 130], ["라프라스", 131]], [["이브이", 133], ["쥬피썬더", 135], ["부스터", 136]], [["뿔충이", 13], ["딱충이", 14], ["독침붕", 15]], [["모다피", 69], ["우츠동", 70], ["우츠보트", 71]], [["캐터피", 10], ["단데기", 11], ["버터플", 12]], [["메탕", 374], ["메탕구", 375], ["메타그로스", 376]], [["루리리", 298], ["마릴", 183], ["마릴리", 184]], [["딥상어동", 443], ["한바이트", 444], ["한카리아스", 445]],
];
const special = [["뮤", 151, "rare"], ["뮤츠", 150, "rare"], ["썬더", 145, "rare"], ["프리져", 144, "legend"], ["파이어", 146, "legend"], ["루기아", 249, "legend"], ["칠색조", 250, "legend"], ["아르세우스", 493, "legend"], ["기라티나", 487, "rare"], ["세레비", 251, "rare"]];
const cardPlans = {
  1: [{ points: 0, pattern: [1, 1, 1] }, { points: 0, pattern: [2, 1] }, { points: 0, pattern: [1, 1, 1, 1] }, { points: 0, pattern: [2, 2] }, { points: 0, pattern: [3] }, { points: 0, pattern: [2, 1, 1] }, { points: 1, pattern: [4] }, { points: 1, pattern: [3, 2] }, { points: 1, pattern: [2, 2, 2] }],
  2: [{ points: 1, pattern: [3, 2] }, { points: 1, pattern: [2, 2, 2] }, { points: 2, pattern: [5] }, { points: 2, pattern: [4, 3] }, { points: 2, pattern: [3, 2, 2] }, { points: 3, pattern: [6] }, { points: 3, pattern: [5, 3] }, { points: 3, pattern: [3, 3, 3] }],
  3: [{ points: 3, pattern: [6, 3] }, { points: 3, pattern: [4, 3, 3] }, { points: 4, pattern: [7, 3] }, { points: 4, pattern: [5, 4, 3] }, { points: 5, pattern: [7, 4] }, { points: 5, pattern: [5, 4, 4] }],
  rare: [{ points: 4, pattern: [3, 2, 2] }, { points: 4, pattern: [3, 3, 2] }, { points: 5, pattern: [4, 2, 2] }],
  legend: [{ points: 5, pattern: [3, 3, 3] }, { points: 6, pattern: [4, 3, 3] }, { points: 6, pattern: [4, 4, 2] }],
};
const plan = (tier, index) => cardPlans[tier][index % cardPlans[tier].length];
const colors = () => Object.fromEntries(COLORS.map((color) => [color, 0]));
const art = (id) => `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${id}.png`;
const result = (ok, message) => ({ ok, message });
const trainerOf = (target) => TRAINERS.find((entry) => entry.id === target.trainerId) || null;
export const perk = (target, key, fallback) => trainerOf(target)?.perk?.[key] ?? fallback;
export function effectiveCost(target, card) { const discount = card.masterRequired ? perk(target, "specialDiscount", 0) : 0; const out = colors(); COLORS.forEach((color) => { out[color] = Math.max(0, card.cost[color] - discount); }); return out; }
export function badgeRequirement(target, badge) { const relief = perk(target, "badgeRelief", 0); const need = colors(); COLORS.forEach((color) => { need[color] = Math.max(0, (badge.need[color] || 0) - relief); }); return need; }

function shuffle(items, random) { const output = [...items]; for (let index = output.length - 1; index > 0; index -= 1) { const swap = Math.floor(random() * (index + 1)); [output[index], output[swap]] = [output[swap], output[index]]; } return output; }
function makeCost(tier, index) { const cost = colors(); plan(tier, index).pattern.forEach((amount, offset) => { cost[COLORS[(index + offset + (typeof tier === "number" ? tier : 0)) % COLORS.length]] = amount; }); return cost; }
function makeCard(tier, index, family, stage, kind = "normal") { const [name, artId] = family[stage - 1]; return { id: `${tier}-${index + 1}`, name, artwork: art(artId), tier, stage, line: family.map(([entry]) => entry).join("/"), bonus: COLORS[(index + stage) % COLORS.length], bonusCount: kind === "normal" ? 1 : 2, points: plan(tier, index).points, cost: makeCost(tier, index), kind, masterRequired: kind !== "normal" }; }
function makeDeck(tier, count) { return Array.from({ length: count }, (_, index) => makeCard(tier, index, families[index % families.length], Math.min(tier, 3))); }
function makeSpecial(kind, entries) { return entries.map(([name, artId], index) => ({ id: `${kind}-${index + 1}`, name, artwork: art(artId), tier: kind, stage: 0, line: name, bonus: COLORS[index % COLORS.length], bonusCount: 2, points: plan(kind, index).points, cost: makeCost(kind, index), kind, masterRequired: true })); }
function draw(game, tier) { const card = game.decks[tier].pop(); if (card) game.market[tier].push(card); }
function player(game, index) { return game.players[index]; }
function total(target) { return Object.values(target.tokens).reduce((sum, value) => sum + value, 0); }
function active(game, index) { return !game.finished && !game.pending && game.active === index; }
export function evolutionPayment(target, card) { const spend = colors(); let wild = 0; const discount = perk(target, "evolutionDiscount", EVOLUTION_DISCOUNT); COLORS.forEach((color) => { const required = Math.max(0, card.cost[color] - target.bonuses[color] - discount); const paid = Math.min(required, target.tokens[color]); spend[color] = paid; wild += required - paid; }); return wild <= target.tokens.wild ? { spend, wild } : null; }
function availableEvolution(game, index) { const target = player(game, index); const owned = target.cards.concat(target.evolutions); return Object.values(game.market).flat().concat(target.reserved).filter((card) => card.kind === "normal" && card.stage > 1 && owned.some((ownedCard) => ownedCard.line === card.line && ownedCard.stage === card.stage - 1) && evolutionPayment(target, card) !== null); }
function claimBadge(game, index) { const target = player(game, index); const badge = game.badges.find((entry) => entry.owner === null && COLORS.every((color) => target.bonuses[color] >= badgeRequirement(target, entry)[color])); if (!badge) return null; badge.owner = index; target.badges.push(badge); target.score += badge.points; if (target.score >= WIN_SCORE && game.finalRoundPlayer === null) game.finalRoundPlayer = index; return badge; }
function endTurn(game, index, prefix = "") { const badge = claimBadge(game, index); advanceTurn(game); if (game.finished) return; const parts = []; if (prefix) parts.push(prefix); if (badge) parts.push(`${player(game, index).name} · ${badge.icon} ${badge.name} 획득! ★${badge.points}`); parts.push(`${player(game, game.active).name}의 차례입니다.`); game.log = parts.join(" · "); }
function advanceTurn(game) { game.pending = null; game.evolvedThisTurn = false; game.active = (game.active + 1) % game.playerCount; if (game.active === 0) game.turn += 1; if (game.finalRoundPlayer === game.active) finish(game); else game.log = `${player(game, game.active).name}의 차례입니다.`; }
function finishTurn(game, index) { const choices = availableEvolution(game, index); if (choices.length && !game.evolvedThisTurn) { game.pending = { type: "evolution", player: index, choices: choices.map((card) => card.id) }; game.log = "진화할 포켓몬을 한 장 선택하거나 건너뛰세요."; return; } endTurn(game, index); }
function afterAction(game, index) { const excess = total(player(game, index)) - perk(player(game, index), "tokenLimit", 10); if (excess > 0) { game.pending = { type: "return", player: index, count: excess }; game.log = `포켓볼을 ${excess}개 반납하세요. (보유 한도 ${perk(player(game, index), "tokenLimit", 10)}개)`; return; } finishTurn(game, index); }
function finish(game) { const ranked = [...game.players].sort((left, right) => right.score - left.score || right.badges.length - left.badges.length || right.evolutions.length - left.evolutions.length || right.cards.length - left.cards.length || left.seat - right.seat); game.finished = true; game.winner = ranked[0].seat; game.log = `${ranked[0].name} 승리! 명성 ${ranked[0].score} · 배지 ${ranked[0].badges.length}개 · 진화 ${ranked[0].evolutions.length}장`; }
function findCard(game, index, id) { const target = player(game, index); for (const tier of Object.keys(game.market)) { const cardIndex = game.market[tier].findIndex((card) => card.id === id); if (cardIndex >= 0) return { collection: game.market[tier], cardIndex, tier, target }; } const cardIndex = target.reserved.findIndex((card) => card.id === id); return cardIndex >= 0 ? { collection: target.reserved, cardIndex, tier: null, target } : null; }

export function createGame(playerCount, random = Math.random, trainerIds = []) {
  if (![2, 3, 4].includes(playerCount)) throw new Error("플레이어 수는 2~4명이어야 합니다.");
  const pool = shuffle(TRAINERS, random);
  const used = new Set();
  const roster = Array.from({ length: playerCount }, (_, seat) => {
    const picked = TRAINERS.find((entry) => entry.id === trainerIds[seat] && !used.has(entry.id));
    if (picked) { used.add(picked.id); return picked; }
    return null;
  });
  roster.forEach((entry, seat) => { if (entry) return; const next = pool.find((candidate) => !used.has(candidate.id)); used.add(next.id); roster[seat] = next; });
  const supply = playerCount === 2 ? 4 : playerCount === 3 ? 5 : 7;
  const rare = special.filter((entry) => entry[2] === "rare").map(([name, artId]) => [name, artId]);
  const legend = special.filter((entry) => entry[2] === "legend").map(([name, artId]) => [name, artId]);
  const game = { playerCount, active: 0, turn: 1, pending: null, finished: false, winner: null, finalRoundPlayer: null, evolvedThisTurn: false, bank: { red: supply, blue: supply, yellow: supply, green: supply, black: supply, wild: 7 }, decks: { 1: shuffle(makeDeck(1, 35), random), 2: shuffle(makeDeck(2, 30), random), 3: shuffle(makeDeck(3, 15), random), rare: shuffle(makeSpecial("rare", rare), random), legend: shuffle(makeSpecial("legend", legend), random) }, market: { 1: [], 2: [], 3: [], rare: [], legend: [] }, badges: shuffle(BADGES, random).slice(0, playerCount + 1).map((badge) => ({ ...badge, owner: null })), players: Array.from({ length: playerCount }, (_, seat) => ({ seat, name: roster[seat].name, trainerId: roster[seat].id, title: roster[seat].title, avatar: roster[seat].avatar, score: 0, tokens: { ...colors(), wild: 0 }, bonuses: { ...colors(), [roster[seat].bonus]: 1 }, cards: [], reserved: [], evolutions: [], badges: [] })), log: "게임 시작! 포켓볼을 가져오거나 포켓몬을 포획하세요." };
  Object.keys(game.market).forEach((tier) => { for (let index = 0; index < (tier === "rare" || tier === "legend" ? 2 : 4); index += 1) draw(game, tier); });
  return game;
}

export function takeTokens(game, index, selected) { if (!active(game, index)) return result(false, "지금 수행할 수 없는 행동입니다."); if (!Array.isArray(selected) || selected.length < 1 || selected.length > 3 || selected.some((color) => !COLORS.includes(color))) return result(false, "가져올 포켓볼을 선택하세요."); const distinct = new Set(selected).size; const double = selected.length === 2 && distinct === 1 && game.bank[selected[0]] >= perk(player(game, index), "sameColorThreshold", 4); const varied = distinct === selected.length && selected.length <= 3; if (!double && !varied) return result(false, `서로 다른 색 최대 3개 또는 ${perk(player(game, index), "sameColorThreshold", 4)}개 이상 남은 같은 색 2개만 가져올 수 있습니다.`); if (selected.some((color) => game.bank[color] < selected.filter((entry) => entry === color).length)) return result(false, "공급처에 포켓볼이 부족합니다."); selected.forEach((color) => { game.bank[color] -= 1; player(game, index).tokens[color] += 1; }); afterAction(game, index); return result(true, "포켓볼을 가져왔습니다."); }
export function reserveCard(game, index, tier, id = null) { if (!active(game, index)) return result(false, "지금 수행할 수 없는 행동입니다."); if (![1, 2, 3].includes(Number(tier))) return result(false, "희귀·전설·환상 카드는 보관할 수 없습니다."); const target = player(game, index); const reserveLimit = perk(target, "reserveLimit", 3); if (target.reserved.length >= reserveLimit) return result(false, `손에는 최대 ${reserveLimit}장만 보관할 수 있습니다.`); const market = game.market[tier]; const cardIndex = id ? market.findIndex((card) => card.id === id) : -1; const card = cardIndex >= 0 ? market.splice(cardIndex, 1)[0] : game.decks[tier].pop(); if (!card) return result(false, "보관할 카드가 없습니다."); if (cardIndex >= 0) draw(game, tier); target.reserved.push(card); const grant = Math.min(perk(target, "reserveWild", 1), game.bank.wild); game.bank.wild -= grant; target.tokens.wild += grant; afterAction(game, index); return result(true, "카드를 손에 보관했습니다."); }
export function buyCard(game, index, id) { if (!active(game, index)) return result(false, "지금 수행할 수 없는 행동입니다."); const found = findCard(game, index, id); if (!found) return result(false, "카드를 찾을 수 없습니다."); const card = found.collection[found.cardIndex]; const target = found.target; const cost = effectiveCost(target, card); const wildNeeded = COLORS.reduce((sum, color) => sum + Math.max(0, cost[color] - target.bonuses[color] - target.tokens[color]), 0); if (!card.masterRequired && wildNeeded > 0) return result(false, "포켓볼이 부족합니다. 마스터볼은 희귀·전설 포켓몬 포획에만 사용할 수 있습니다."); if (card.masterRequired && wildNeeded + 1 > target.tokens.wild) return result(false, "마스터볼이 부족합니다. 카드를 손에 보관하면 마스터볼을 받습니다."); COLORS.forEach((color) => { const required = Math.max(0, cost[color] - target.bonuses[color]); const spent = Math.min(required, target.tokens[color]); target.tokens[color] -= spent; game.bank[color] += spent; const useWild = required - spent; target.tokens.wild -= useWild; game.bank.wild += useWild; }); if (card.masterRequired && target.tokens.wild > 0) { target.tokens.wild -= 1; game.bank.wild += 1; } found.collection.splice(found.cardIndex, 1); if (found.tier) draw(game, found.tier); target.cards.push(card); target.bonuses[card.bonus] += card.bonusCount; target.score += card.points + (Number(card.tier) === 3 ? perk(target, "tierThreeBonus", 0) : 0); if (target.score >= WIN_SCORE && game.finalRoundPlayer === null) game.finalRoundPlayer = index; afterAction(game, index); return result(true, "포켓몬을 포획했습니다."); }
export function returnTokens(game, index, tokens) { if (game.pending?.type !== "return" || game.pending.player !== index) return result(false, "반납할 포켓볼이 없습니다."); const totalReturn = COLORS.concat("wild").reduce((sum, color) => sum + (tokens?.[color] || 0), 0); if (totalReturn !== game.pending.count || COLORS.concat("wild").some((color) => !Number.isInteger(tokens?.[color] || 0) || (tokens?.[color] || 0) < 0 || (tokens?.[color] || 0) > player(game, index).tokens[color])) return result(false, "반납할 포켓볼 수가 맞지 않습니다."); COLORS.concat("wild").forEach((color) => { const amount = tokens[color] || 0; player(game, index).tokens[color] -= amount; game.bank[color] += amount; }); game.pending = null; finishTurn(game, index); return result(true, "포켓볼을 반납했습니다."); }
export function evolveCard(game, index, id = null) { if (game.pending?.type !== "evolution" || game.pending.player !== index) return result(false, "지금 진화할 수 없습니다."); if (!id) { endTurn(game, index); return result(true, "진화를 건너뛰었습니다."); } if (!game.pending.choices.includes(id)) return result(false, "진화 조건을 충족하지 않습니다."); const target = player(game, index); const found = findCard(game, index, id); if (!found) return result(false, "카드를 찾을 수 없습니다."); const payment = evolutionPayment(target, found.collection[found.cardIndex]); if (!payment) return result(false, "진화에 필요한 포켓볼이 부족합니다."); const [card] = found.collection.splice(found.cardIndex, 1); if (found.tier) draw(game, found.tier); COLORS.forEach((color) => { target.tokens[color] -= payment.spend[color]; game.bank[color] += payment.spend[color]; }); target.tokens.wild -= payment.wild; game.bank.wild += payment.wild; target.evolutions.push(card); target.bonuses[card.bonus] += card.bonusCount; target.score += card.points; if (target.score >= WIN_SCORE && game.finalRoundPlayer === null) game.finalRoundPlayer = index; const message = `${target.name}의 ${card.name} 진화 성공! ★${card.points} 획득`; endTurn(game, index, message); return result(true, message); }
